"use client"

import { Award, BriefcaseBusiness, GraduationCap, Play, Trophy, Users, Swords, type LucideIcon } from "lucide-react"
import { GameHeader } from "@/components/game-header"
import { GameSidebar } from "@/components/game-sidebar"
import { Button } from "@/components/ui/button"
import { useGameState } from "@/lib/save-system"
import { acceptProfessionalOffer, finishYouthSeason, simulateYouthRound, YOUTH_COMPETITIONS } from "@/lib/youth-career-engine"
import { useGameManager } from "@/lib/use-game-manager"
import { hardNavigate } from "@/lib/hard-navigation"
import { saveMatchContext } from "@/lib/match-context"
import { allTeams, getTeamByShort } from "@/lib/teams-data"
import { useTelaGamepad } from "@/hooks/use-tela-gamepad"

export default function YouthCareerPage(){
  // Controle: convencao unica (B volta). Ver hooks/use-tela-gamepad.ts.
  useTelaGamepad({ aoVoltar: () => hardNavigate("/base") })

  const {state,setState}=useGameState(),{initializeNewGame}=useGameManager(),career=state.youthCareer,players=state.youthPlayers??[]
  if(!career)return <main className="min-h-screen bg-[#06090d] text-white"><GameHeader/><div className="p-10 text-center"><p>Nenhuma carreira Sub-20 ativa.</p><Button className="mt-4" onClick={()=>hardNavigate("/novo-jogo")}>Criar carreira</Button></div></main>
  const apply=(next:ReturnType<typeof simulateYouthRound>)=>setState(next)
  const playMatch=()=>{const parent=getTeamByShort(career.clubCurto),pool=allTeams.filter(t=>t.curto!==career.clubCurto&&(!parent?.pais||t.pais===parent.pais)),opponent=pool[(career.round*7+career.currentSeason)%Math.max(1,pool.length)]??allTeams.find(t=>t.curto!==career.clubCurto);if(!opponent)return;saveMatchContext({homeShort:career.clubCurto,awayShort:opponent.curto,homeKit:"home",awayKit:"away",competition:career.currentCompetition??YOUTH_COMPETITIONS[0],round:`Rodada ${career.round+1}`,duration:90,weather:"sunny",matchMode:"normal",friendly:false,youth:true});hardNavigate("/partida/ao-vivo")}
  const toggleStarter=(id:string)=>{const ids=career.startingPlayerIds??players.slice(0,11).map(p=>p.id),next=ids.includes(id)?ids.filter(x=>x!==id):ids.length<11?[...ids,id]:ids;setState({youthCareer:{...career,startingPlayerIds:next}})}
  const accept=(id:string)=>{const offer=career.professionalOffers.find(o=>o.id===id);if(!offer)return;const archived=acceptProfessionalOffer(state,id).youthCareer;initializeNewGame(offer.clubCurto,state.managerName,{youthCareer:archived});hardNavigate("/")}
  return <main className="min-h-screen bg-[#06090d] text-white"><GameHeader/><GameSidebar/>
    <div className="lg:pl-20 pt-20 px-5 pb-12 max-w-[1500px] mx-auto">
      <div className="flex flex-wrap items-end justify-between gap-4 mb-6"><div><p className="text-[#00ffc8] text-xs font-black uppercase tracking-[.25em]">Trajetória na base</p><h1 className="text-3xl font-black mt-1">{career.clubNome}</h1><p className="text-white/50 mt-1">Temporada {career.currentSeason} · {career.currentCompetition??YOUTH_COMPETITIONS[0]}</p></div><div className="flex gap-2"><Button disabled={career.seasonFinished||(career.startingPlayerIds?.length??11)!==11} onClick={playMatch} className="bg-[#00ffc8] text-black hover:bg-[#00d9b0]"><Swords className="w-4 h-4 mr-2"/>Jogar partida</Button><Button disabled={career.seasonFinished} onClick={()=>apply(simulateYouthRound(state))} variant="outline"><Play className="w-4 h-4 mr-2"/>Simular</Button></div></div>
      <section className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3 mb-6">{([
        ["Rodada",`${career.round}/19`,Play],["Pontos",career.points,Trophy],["Campanha",`${career.wins}V ${career.draws}E ${career.losses}D`,Award],["Reputação",Math.round(career.coachReputation),BriefcaseBusiness],["Atletas",players.length,Users],
      ] as [string,string|number,LucideIcon][]).map(([label,value,Icon])=><div key={label} className="rounded-2xl border border-white/10 bg-white/[.04] p-4"><Icon className="w-5 h-5 text-[#00ffc8]"/><p className="text-white/45 text-xs mt-3">{label}</p><p className="text-xl font-black mt-1">{value}</p></div>)}</section>
      {career.seasonFinished&&<section className="rounded-2xl border border-amber-400/30 bg-amber-400/10 p-5 mb-6 flex items-center justify-between gap-4"><div><h2 className="font-black">Temporada concluída</h2><p className="text-sm text-white/60">Finalize para registrar título, formar atletas e receber propostas.</p></div><Button onClick={()=>apply(finishYouthSeason(state))}>Encerrar temporada</Button></section>}
      {career.professionalOffers.length>0&&<section className="mb-6"><h2 className="font-black text-xl mb-3">Propostas para o profissional</h2><div className="grid md:grid-cols-2 gap-3">{career.professionalOffers.map(o=><div key={o.id} className="rounded-2xl border border-[#00ffc8]/25 bg-[#00ffc8]/5 p-5 flex items-center justify-between gap-4"><div><p className="font-black">{o.clubNome}</p><p className="text-xs text-white/50">{o.role==="head_coach"?"Técnico principal":"Comissão profissional"} · R$ {o.monthlySalary.toLocaleString("pt-BR")}/mês · {o.contractMonths} meses</p><p className="mt-2 text-[11px] text-white/40">Metas: {o.objectives.join(" · ")}</p></div><Button onClick={()=>accept(o.id)}>Aceitar</Button></div>)}</div></section>}
      <div className="grid lg:grid-cols-2 gap-5"><section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><div className="flex items-center justify-between gap-3"><h2 className="font-black text-xl flex items-center gap-2"><GraduationCap className="text-[#00ffc8]"/>Elenco Sub-20</h2><select value={career.formation??"4-3-3"} onChange={e=>setState({youthCareer:{...career,formation:e.target.value}})} className="rounded-lg bg-black/50 border border-white/10 p-2 text-xs"><option>4-3-3</option><option>4-4-2</option><option>4-2-3-1</option><option>3-5-2</option></select></div><p className="mt-2 text-xs text-white/40">Selecione exatamente 11 titulares. A escalação, formação e banco serão usados na partida ao vivo.</p><div className="mt-4 space-y-2 max-h-[430px] overflow-auto">{players.toSorted((a,b)=>b.potential-a.potential).map(p=>{const starter=(career.startingPlayerIds??players.slice(0,11).map(x=>x.id)).includes(p.id);return <button onClick={()=>toggleStarter(p.id)} key={p.id} className={`w-full grid grid-cols-[auto_1fr_auto_auto] items-center gap-4 rounded-xl p-3 text-left ${starter?"bg-[#00ffc8]/10 border border-[#00ffc8]/25":"bg-black/30 border border-transparent"}`}><span className={`text-[9px] font-black ${starter?"text-[#00ffc8]":"text-white/25"}`}>{starter?"TIT":"RES"}</span><div><p className="font-bold">{p.name}</p><p className="text-xs text-white/40">{p.position} · {p.age} anos</p></div><b>{p.overall}</b><span className="text-[#00ffc8]">POT {p.potential}</span></button>})}</div></section>
      <section className="rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-black text-xl">Seu legado</h2><p className="text-sm text-white/45 mt-1">Atletas treinados por você continuam sendo acompanhados após sair da base.</p><div className="mt-4 space-y-2 max-h-[430px] overflow-auto">{career.alumni.length===0?<p className="text-white/35 py-10 text-center">Conclua uma temporada para formar sua primeira geração.</p>:career.alumni.map(a=><div key={a.playerId} className="rounded-xl bg-black/30 p-3"><div className="flex justify-between gap-3"><b>{a.playerName}</b><span className="text-[#00ffc8] text-sm">{a.currentClub}</span></div><p className="text-xs text-white/45 mt-1">{a.nationalTeamCaps} jogos pela seleção · {a.careerTitles.length} títulos · {a.worldCupTitles} Copa do Mundo</p></div>)}</div></section></div>
    </div></main>
}
