// Mapeamento centralizado de escudos
// Este arquivo nao deve importar de teams-data.ts ou international-teams.ts para evitar dependencias circulares

import { gameAssetUrl } from "@/lib/game-asset"

const ULTRAFOOT_RAW_URL = "https://raw.githubusercontent.com/jovemegidio/Ultrafoot/main"

// Mapeamento de file_keys para nomes de arquivos de escudos no repositorio
const escudoMap: Record<string, string> = {
  "botafogorj_bra": "botafogo",
  "flarj": "flamengo",
  "flurj": "fluminense",
  "vasco": "vasco",
  "corinthians_bra": "corinthians",
  "saopaulo_bra": "saopaulo",
  "palmeiras": "palmeiras",
  "santos": "santos",
  "gremio": "gremio",
  "internacional_bra": "internacional",
  "atleticomg_bra": "atleticomg",
  "cruzeiro_bra": "cruzeiro",
  "atleticopr_bra": "atleticopr",
  "coritiba_bra": "coritiba",
  "bahia": "bahia",
  "fortaleza": "fortaleza",
  "ceara_bra": "ceara",
  "sport": "sport",
  "vitoria": "vitoria",
  "bragantino_bra": "bragantino",
  "cuiaba": "cuiaba",
  "goias": "goias",
  "juventude": "juventude",
}

// Mapeamento de file_keys para escudos locais
const localEscudoMap: Record<string, string> = {
  // Serie A - arquivos raiz nomeados por file_key (confiáveis)
  "botafogorj_bra": "/escudos/botafogorj_bra.png",
  "palmeiras": "/escudos/palmeiras.png",
  "flarj": "/escudos/flarj.png",
  "corinthians_bra": "/escudos/corinthians_bra.png",
  "saopaulo_bra": "/escudos/saopaulo_bra.png",
  "flurj": "/escudos/flurj.png",
  "vasco": "/escudos/vasco.png",
  "santos": "/escudos/santos.png",
  "gremio": "/escudos/gremio.png",
  "internacional_bra": "/escudos/internacional_bra.png",
  "atleticomg_bra": "/escudos/atleticomg_bra.png",
  "cruzeiro_bra": "/escudos/cruzeiro_bra.png",
  "bahia": "/escudos/bahia.png",
  "fortaleza": "/escudos/fortaleza.png",
  "vitoria": "/escudos/vitoria.png",
  "atleticopr_bra": "/escudos/atleticopr_bra.png",
  "ceara_bra": "/escudos/ceara_bra.png",
  "sport": "/escudos/sport.png",
  "bragantino_bra": "/escudos/bragantino_bra.png",
  "juventude": "/escudos/juventude.png",
  "miirassol_sp": "/escudos/miirassol_sp.png",
  // Serie B - existentes
  "americamg_bra": "/escudos/americamg_bra.png",
  "goias": "/escudos/goias.png",
  "coritiba_bra": "/escudos/coritiba_bra.png",
  "crb_bra": "/escudos/crb_bra.png",
  "avai_bra": "/escudos/avai_bra.png",
  "paysandu": "/escudos/paysandu.png",
  "chapecoense_bra": "/escudos/chapecoense_bra.png",
  "vilago": "/escudos/vilago.png",
  "amazonas_am": "/escudos/amazonas_am.png",
  "operario_pr": "/escudos/operario_pr.png",
  "novorinzontino_sp": "/escudos/novorinzontino_sp.png",
  "botafogosp_bra": "/escudos/botafogosp_bra.png",
  // Serie B - novos
  "saobernardo_sp": "/escudos/saobernardo_sp.png",
  "guaranisp_bra": "/escudos/guaranisp_bra.png",
  "pontepreta_bra": "/escudos/pontepreta_bra.png",
  "criciuma_bra": "/escudos/criciuma_bra.png",
  "cuiaba_bra": "/escudos/cuiaba_bra.png",
  "atleticogo_bra": "/escudos/atleticogo_bra.png",
  "ituano_sp": "/escudos/ituano_sp.png",
  "aguasanta_sp": "/escudos/aguasantasp_bra.png",
  // Serie C
  "remo_pa": "/escudos/remo.png",
  "abc_rn": "/escudos/abcrn_bra.png",
  "nautico_pe": "/escudos/nautico.png",
  "santacruz_pe": "/escudos/santa.png",
  "csa_al": "/escudos/csa_bra.png",
  "sampaio_ma": "/escudos/samapaiocorrea_ma.png",
  "figueirense_sc": "/escudos/figueirense.png",
  "londrina_pr": "/escudos/londrina_pr.png",
  "tombense_mg": "/escudos/tombense_mg.png",
  "botafogo_pb": "/escudos/botafogopb_bra.png",
  "aparecidense_go": "/escudos/aparecidense_go.png",
  "ferroviario_ce": "/escudos/ferroviarioce_bra.png",
  "confianca_se": "/escudos/confianca_se.png",
  "voltaredonda_rj": "/escudos/voltaredondarj_bra.png",
  "altos_pi": "/escudos/altos_pi.png",
  "floresta_ce": "/escudos/florestace.png",
  "ypiranga_rs": "/escudos/ypiranga_rs.png",
  "saojose_rs": "/escudos/saojosers_bra.png",
  "athletic_mg": "/escudos/athleticclub_mg.png",
  "caxias_rs": "/escudos/caxias.png",
  // Serie D
  "brasiliense_df": "/escudos/brasiliense_df_bra.png",
  "river_pi": "/escudos/riverpi_bra.png",
  "inter_sp": "/escudos/interlimeira.png",
  "portovelho_ro": "/escudos/portovelho.png",
  "trem_ap": "/escudos/ap_trem.png",
  "saoraimundo_am": "/escudos/saoraimundo_am_bra.png",
  "realnoroeste_es": "/escudos/realnoroeste_es.png",
  "novaiguacu_rj": "/escudos/novaiguacu_rj.png",
  "motoclub_ma": "/escudos/motoclubma_bra.png",
  "guarany_ce": "/escudos/guaranysobral_bra.png",
  // Premier League
  "manchester_city": "/escudos/premier_league/manchester_city.png",
  "arsenal": "/escudos/premier_league/arsenal.png",
  "liverpool": "/escudos/premier_league/liverpool.png",
  "manchester_united": "/escudos/premier_league/manchester_united.png",
  "chelsea": "/escudos/premier_league/chelsea.png",
  "tottenham": "/escudos/premier_league/tottenham.png",
  "newcastle": "/escudos/premier_league/newcastle.png",
  "aston_villa": "/escudos/premier_league/aston_villa.png",
  "west_ham": "/escudos/premier_league/west_ham.png",
  "brighton": "/escudos/premier_league/brighton.png",
  "everton": "/escudos/premier_league/everton.png",
  "crystal_palace": "/escudos/premier_league/crystal_palace.png",
  "bournemouth": "/escudos/premier_league/bournemouth.png",
  "wolves": "/escudos/premier_league/wolves.png",
  "fulham": "/escudos/premier_league/fulham.png",
  "brentford": "/escudos/premier_league/brentford.png",
  "nottingham_forest": "/escudos/premier_league/nottingham_forest.png",
  "leicester": "/escudos/premier_league/leicester.png",
  "southampton": "/escudos/premier_league/southampton.png",
  "ipswich": "/escudos/premier_league/ipswich.png",
  // La Liga
  "real_madrid": "/escudos/la_liga/real_madrid.png",
  "barcelona": "/escudos/la_liga/barcelona.png",
  "atletico_madrid": "/escudos/la_liga/atletico_madrid.png",
  "sevilla": "/escudos/la_liga/sevilla.png",
  "villarreal": "/escudos/la_liga/villarreal.png",
  "real_sociedad": "/escudos/la_liga/real_sociedad.png",
  "athletic_bilbao": "/escudos/la_liga/athletic_bilbao.png",
  "valencia": "/escudos/la_liga/valencia.png",
  "real_betis": "/escudos/la_liga/real_betis.png",
  "girona": "/escudos/la_liga/girona.png",
  "celta_vigo": "/escudos/la_liga/celta_vigo.png",
  "getafe": "/escudos/la_liga/getafe.png",
  "rayo_vallecano": "/escudos/la_liga/rayo_vallecano.png",
  "osasuna": "/escudos/la_liga/osasuna.png",
  "espanyol": "/escudos/la_liga/espanyol.png",
  "las_palmas": "/escudos/la_liga/las_palmas.png",
  "alaves": "/escudos/la_liga/alaves.png",
  "leganes": "/escudos/la_liga/leganes.png",
  "valladolid": "/escudos/la_liga/valladolid.png",
  "mallorca": "/escudos/la_liga/mallorca.png",
  // Serie A Italia
  "inter": "/escudos/serie_a_ita/inter.png",
  "inter_milan": "/escudos/serie_a_ita/inter.png",
  "ac_milan": "/escudos/serie_a_ita/ac_milan.png",
  "juventus": "/escudos/serie_a_ita/juventus.png",
  "napoli": "/escudos/serie_a_ita/napoli.png",
  "roma": "/escudos/serie_a_ita/roma.png",
  "lazio": "/escudos/serie_a_ita/lazio.png",
  "atalanta": "/escudos/serie_a_ita/atalanta.png",
  "fiorentina": "/escudos/serie_a_ita/fiorentina.png",
  "bologna": "/escudos/serie_a_ita/bologna.png",
  "torino": "/escudos/serie_a_ita/torino.png",
  "udinese": "/escudos/serie_a_ita/udinese.png",
  "genoa": "/escudos/serie_a_ita/genoa.png",
  "verona": "/escudos/serie_a_ita/verona.png",
  "hellas_verona": "/escudos/serie_a_ita/verona.png",
  "sassuolo": "/escudos/serie_a_ita/sassuolo.png",
  "empoli": "/escudos/serie_a_ita/empoli.png",
  "lecce": "/escudos/serie_a_ita/lecce.png",
  "cagliari": "/escudos/serie_a_ita/cagliari.png",
  "como": "/escudos/serie_a_ita/como.png",
  "parma": "/escudos/serie_a_ita/parma.png",
  "venezia": "/escudos/serie_a_ita/venezia.png",
  "monza": "/escudos/monza_ita.png",
  // Bundesliga
  "bayern_munich": "/escudos/bundesliga/bayern_munich.png",
  "borussia_dortmund": "/escudos/bundesliga/borussia_dortmund.png",
  "rb_leipzig": "/escudos/bundesliga/rb_leipzig.png",
  "bayer_leverkusen": "/escudos/bundesliga/bayer_leverkusen.png",
  "eintracht_frankfurt": "/escudos/bundesliga/eintracht_frankfurt.png",
  "freiburg": "/escudos/bundesliga/freiburg.png",
  "wolfsburg": "/escudos/bundesliga/wolfsburg.png",
  "borussia_monchengladbach": "/escudos/bundesliga/borussia_monchengladbach.png",
  "borussia_mgladbach": "/escudos/bundesliga/borussia_monchengladbach.png",
  "werder_bremen": "/escudos/bundesliga/werder_bremen.png",
  "hoffenheim": "/escudos/bundesliga/hoffenheim.png",
  "union_berlin": "/escudos/bundesliga/union_berlin.png",
  "mainz": "/escudos/bundesliga/mainz.png",
  "vfb_stuttgart": "/escudos/bundesliga/vfb_stuttgart.png",
  "stuttgart": "/escudos/bundesliga/vfb_stuttgart.png",
  "fc_koln": "/escudos/bundesliga/fc_koln.png",
  "augsburg": "/escudos/bundesliga/augsburg.png",
  "bochum": "/escudos/bundesliga/bochum.png",
  "heidenheim": "/escudos/bundesliga/heidenheim.png",
  "darmstadt": "/escudos/bundesliga/darmstadt.png",
  // Ligue 1
  "psg": "/escudos/ligue_1/psg.png",
  "monaco": "/escudos/ligue_1/monaco.png",
  "marseille": "/escudos/ligue_1/marseille.png",
  "lille": "/escudos/ligue_1/lille.png",
  "lyon": "/escudos/ligue_1/lyon.png",
  "rennes": "/escudos/ligue_1/rennes.png",
  "nice": "/escudos/ligue_1/nice.png",
  "lens": "/escudos/ligue_1/lens.png",
  "reims": "/escudos/ligue_1/reims.png",
  "nantes": "/escudos/ligue_1/nantes.png",
  "strasbourg": "/escudos/ligue_1/strasbourg.png",
  "montpellier": "/escudos/ligue_1/montpellier.png",
  "angers": "/escudos/ligue_1/angers.png",
  "toulouse": "/escudos/ligue_1/toulouse.png",
  "brest": "/escudos/ligue_1/brest.png",
  "auxerre": "/escudos/ligue_1/auxerre.png",
  "le_havre": "/escudos/ligue_1/le_havre.png",
  "saint_etienne": "/escudos/ligue_1/saint_etienne.png",
  // Saudi Pro League
  "al_hilal": "/escudos/saudi_pro/al_hilal.png",
  "al_nassr": "/escudos/saudi_pro/al_nassr.png",
  "al_ittihad": "/escudos/saudi_pro/al_ittihad.png",
  "al_ahli": "/escudos/saudi_pro/al_ahli.png",
  "al_ahli_saudi": "/escudos/saudi_pro/al_ahli.png",
  "al_shabab": "/escudos/saudi_pro/al_shabab.png",
  "al_taawoun": "/escudos/saudi_pro/al_taawoun.png",
  "al_fateh": "/escudos/saudi_pro/al_fateh.png",
  "al_fayha": "/escudos/saudi_pro/al_fayha.png",
  "al_ettifaq": "/escudos/saudi_pro/al_ettifaq.png",
  "damac": "/escudos/saudi_pro/damac.png",
  "al_riyadh": "/escudos/saudi_pro/al_riyadh.png",
  "al_khaleej": "/escudos/saudi_pro/al_khaleej.png",
  "al_raed": "/escudos/saudi_pro/al_raed.png",
  "al_hazm": "/escudos/saudi_pro/al_hazm.png",
  "al_orobah": "/escudos/saudi_pro/al_orobah.png",
  "al_akhdoud": "/escudos/saudi_pro/al_akhdoud.png",
  "al_wehda": "/escudos/saudi_pro/al_wehda.png",
  "al_qadisiyah": "/escudos/saudi_pro/al_qadisiyah.png",
  // MLS
  "inter_miami": "/escudos/mls/inter_miami.png",
  "la_galaxy": "/escudos/mls/la_galaxy.png",
  "lafc": "/escudos/mls/lafc.png",
  "atlanta_united": "/escudos/mls/atlanta_united.png",
  "seattle_sounders": "/escudos/mls/seattle_sounders.png",
  "new_york_city": "/escudos/mls/new_york_city.png",
  "new_york_red_bulls": "/escudos/mls/new_york_red_bulls.png",
  "ny_red_bulls": "/escudos/mls/new_york_red_bulls.png",
  "nycfc": "/escudos/mls/new_york_city.png",
  "toronto_fc": "/escudos/mls/toronto_fc.png",
  "cf_montreal": "/escudos/mls/cf_montreal.png",
  "austin_fc": "/escudos/mls/austin_fc.png",
  "columbus_crew": "/escudos/mls/columbus_crew.png",
  "fc_cincinnati": "/escudos/mls/fc_cincinnati.png",
  "nashville_sc": "/escudos/mls/nashville_sc.png",
  "orlando_city": "/escudos/mls/orlando_city.png",
  "philadelphia_union": "/escudos/mls/philadelphia_union.png",
  "portland_timbers": "/escudos/mls/portland_timbers.png",
  "minnesota_united": "/escudos/mls/minnesota_united.png",
  "charlotte_fc": "/escudos/mls/charlotte_fc.png",
  "dc_united": "/escudos/mls/dc_united.png",
  "houston_dynamo": "/escudos/mls/houston_dynamo.png",
  // Liga MX
  "club_america": "/escudos/liga_mx/club_america.png",
  "chivas": "/escudos/liga_mx/chivas.png",
  "cruz_azul": "/escudos/liga_mx/cruz_azul.png",
  "tigres": "/escudos/liga_mx/tigres.png",
  "monterrey": "/escudos/liga_mx/monterrey.png",
  "pumas": "/escudos/liga_mx/pumas.png",
  "leon": "/escudos/liga_mx/leon.png",
  "santos_laguna": "/escudos/liga_mx/santos_laguna.png",
  "toluca": "/escudos/liga_mx/toluca.png",
  "pachuca": "/escudos/liga_mx/pachuca.png",
  "atlas": "/escudos/liga_mx/atlas.png",
  "necaxa": "/escudos/liga_mx/necaxa.png",
  "queretaro": "/escudos/liga_mx/queretaro.png",
  "tijuana": "/escudos/liga_mx/tijuana.png",
  "puebla": "/escudos/liga_mx/puebla.png",
  "mazatlan": "/escudos/liga_mx/mazatlan.png",
  "san_luis": "/escudos/liga_mx/san_luis.png",
  "fc_juarez": "/escudos/liga_mx/fc_juarez.png",
  // Primeira Liga Portugal
  "benfica": "/escudos/primeira_liga/benfica.png",
  "porto": "/escudos/primeira_liga/porto.png",
  "sporting": "/escudos/primeira_liga/sporting.png",
  "braga": "/escudos/primeira_liga/braga.png",
  "vitoria_guimaraes": "/escudos/primeira_liga/vitoria_guimaraes.png",
  "boavista": "/escudos/primeira_liga/boavista.png",
  "santa_clara": "/escudos/primeira_liga/santa_clara.png",
  "famalicao": "/escudos/primeira_liga/famalicao.png",
  "rio_ave": "/escudos/primeira_liga/rio_ave.png",
  "casa_pia": "/escudos/primeira_liga/casa_pia.png",
  "moreirense": "/escudos/primeira_liga/moreirense.png",
  "gil_vicente": "/escudos/primeira_liga/gil_vicente.png",
  "arouca": "/escudos/primeira_liga/arouca.png",
  "estoril": "/escudos/primeira_liga/estoril.png",
  "nacional": "/escudos/primeira_liga/nacional.png",
  "estrela_amadora": "/escudos/primeira_liga/estrela_amadora.png",
  "farense": "/escudos/primeira_liga/farense.png",
  "avs": "/escudos/primeira_liga/avs.png",
  // Bundesliga extras
  "st_pauli": "/escudos/bundesliga/st_pauli.png",
  "holstein_kiel": "/escudos/bundesliga/holstein_kiel.png",
  // Ligue 1 extras
  "lorient": "/escudos/ligue_1/lorient.png",
  "clermont": "/escudos/ligue_1/clermont.png",
}

export function getEscudoUrl(fileKey: string): string {
  const raw = localEscudoMap[fileKey] ?? `/escudos/${fileKey}.png`
  return gameAssetUrl(raw)
}

export function getRemoteEscudoUrl(fileKey: string): string {
  const key = escudoMap[fileKey] || fileKey
  return `${ULTRAFOOT_RAW_URL}/teams/escudos/${key}.png`
}

export function getEscudoMiniUrl(fileKey: string): string {
  const raw = localEscudoMap[fileKey] ?? `/escudos/${fileKey}.png`
  return gameAssetUrl(raw)
}
