// Dados dos times internacionais
import { type Team, type Divisao } from "./teams-data"
import { getEscudoUrl } from "./escudos-map"

// Usa a funcao centralizada de escudos que verifica primeiro os locais
function getIntlEscudo(key: string): string {
  return getEscudoUrl(key)
}

// =============================================
// PREMIER LEAGUE - INGLATERRA
// =============================================
export const premierLeagueTeams: Team[] = [
  {
    nome: "Manchester City",
    curto: "MCI",
    cidade: "Manchester",
    estado: "Inglaterra",
    cor1: "#6CABDD",
    cor2: "#1C2C5B",
    prestigio: 95,
    torcida: 500000000,
    estadio_cap: 53400,
    saldo: 850000000,
    file_key: "manchester_city",
    estadio_nome: "Etihad Stadium",
    patrocinador: "Etihad Airways",
    escudo_url: getIntlEscudo("manchester_city"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Arsenal",
    curto: "ARS",
    cidade: "Londres",
    estado: "Inglaterra",
    cor1: "#EF0107",
    cor2: "#FFFFFF",
    prestigio: 92,
    torcida: 450000000,
    estadio_cap: 60704,
    saldo: 650000000,
    file_key: "arsenal",
    estadio_nome: "Emirates Stadium",
    patrocinador: "Emirates",
    escudo_url: getIntlEscudo("arsenal"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Liverpool",
    curto: "LIV",
    cidade: "Liverpool",
    estado: "Inglaterra",
    cor1: "#C8102E",
    cor2: "#00B2A9",
    prestigio: 93,
    torcida: 480000000,
    estadio_cap: 61276,
    saldo: 700000000,
    file_key: "liverpool",
    estadio_nome: "Anfield",
    patrocinador: "Standard Chartered",
    escudo_url: getIntlEscudo("liverpool"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Manchester United",
    curto: "MUN",
    cidade: "Manchester",
    estado: "Inglaterra",
    cor1: "#DA291C",
    cor2: "#FBE122",
    prestigio: 90,
    torcida: 600000000,
    estadio_cap: 74310,
    saldo: 600000000,
    file_key: "manchester_united",
    estadio_nome: "Old Trafford",
    patrocinador: "TeamViewer",
    escudo_url: getIntlEscudo("manchester_united"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Chelsea",
    curto: "CHE",
    cidade: "Londres",
    estado: "Inglaterra",
    cor1: "#034694",
    cor2: "#FFFFFF",
    prestigio: 88,
    torcida: 400000000,
    estadio_cap: 40173,
    saldo: 550000000,
    file_key: "chelsea",
    estadio_nome: "Stamford Bridge",
    patrocinador: "Infinite Athlete",
    escudo_url: getIntlEscudo("chelsea"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Tottenham",
    curto: "TOT",
    cidade: "Londres",
    estado: "Inglaterra",
    cor1: "#132257",
    cor2: "#FFFFFF",
    prestigio: 85,
    torcida: 250000000,
    estadio_cap: 62850,
    saldo: 450000000,
    file_key: "tottenham",
    estadio_nome: "Tottenham Hotspur Stadium",
    patrocinador: "AIA",
    escudo_url: getIntlEscudo("tottenham"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Newcastle United",
    curto: "NEW",
    cidade: "Newcastle",
    estado: "Inglaterra",
    cor1: "#241F20",
    cor2: "#FFFFFF",
    prestigio: 82,
    torcida: 150000000,
    estadio_cap: 52305,
    saldo: 400000000,
    file_key: "newcastle",
    estadio_nome: "St James' Park",
    patrocinador: "Sela",
    escudo_url: getIntlEscudo("newcastle"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Aston Villa",
    curto: "AVL",
    cidade: "Birmingham",
    estado: "Inglaterra",
    cor1: "#670E36",
    cor2: "#95BFE5",
    prestigio: 80,
    torcida: 100000000,
    estadio_cap: 42749,
    saldo: 350000000,
    file_key: "aston_villa",
    estadio_nome: "Villa Park",
    patrocinador: "Betano",
    escudo_url: getIntlEscudo("aston_villa"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Brighton",
    curto: "BHA",
    cidade: "Brighton",
    estado: "Inglaterra",
    cor1: "#0057B8",
    cor2: "#FFFFFF",
    prestigio: 75,
    torcida: 50000000,
    estadio_cap: 31800,
    saldo: 250000000,
    file_key: "brighton",
    estadio_nome: "Amex Stadium",
    patrocinador: "American Express",
    escudo_url: getIntlEscudo("brighton"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "West Ham",
    curto: "WHU",
    cidade: "Londres",
    estado: "Inglaterra",
    cor1: "#7A263A",
    cor2: "#1BB1E7",
    prestigio: 76,
    torcida: 80000000,
    estadio_cap: 62500,
    saldo: 280000000,
    file_key: "west_ham",
    estadio_nome: "London Stadium",
    patrocinador: "Betway",
    escudo_url: getIntlEscudo("west_ham"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Crystal Palace",
    curto: "CRY",
    cidade: "Londres",
    estado: "Inglaterra",
    cor1: "#1B458F",
    cor2: "#C4122E",
    prestigio: 72,
    torcida: 40000000,
    estadio_cap: 25486,
    saldo: 180000000,
    file_key: "crystal_palace",
    estadio_nome: "Selhurst Park",
    patrocinador: "Cinch",
    escudo_url: getIntlEscudo("crystal_palace"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Fulham",
    curto: "FUL",
    cidade: "Londres",
    estado: "Inglaterra",
    cor1: "#000000",
    cor2: "#FFFFFF",
    prestigio: 71,
    torcida: 35000000,
    estadio_cap: 22384,
    saldo: 170000000,
    file_key: "fulham",
    estadio_nome: "Craven Cottage",
    patrocinador: "W88",
    escudo_url: getIntlEscudo("fulham"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Wolves",
    curto: "WOL",
    cidade: "Wolverhampton",
    estado: "Inglaterra",
    cor1: "#FDB913",
    cor2: "#231F20",
    prestigio: 73,
    torcida: 45000000,
    estadio_cap: 32050,
    saldo: 200000000,
    file_key: "wolves",
    estadio_nome: "Molineux Stadium",
    patrocinador: "AstroPay",
    escudo_url: getIntlEscudo("wolves"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Bournemouth",
    curto: "BOU",
    cidade: "Bournemouth",
    estado: "Inglaterra",
    cor1: "#DA291C",
    cor2: "#000000",
    prestigio: 70,
    torcida: 30000000,
    estadio_cap: 11364,
    saldo: 150000000,
    file_key: "bournemouth",
    estadio_nome: "Vitality Stadium",
    patrocinador: "Dafabet",
    escudo_url: getIntlEscudo("bournemouth"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Everton",
    curto: "EVE",
    cidade: "Liverpool",
    estado: "Inglaterra",
    cor1: "#003399",
    cor2: "#FFFFFF",
    prestigio: 74,
    torcida: 70000000,
    estadio_cap: 39414,
    saldo: 220000000,
    file_key: "everton",
    estadio_nome: "Goodison Park",
    patrocinador: "Stake",
    escudo_url: getIntlEscudo("everton"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Brentford",
    curto: "BRE",
    cidade: "Londres",
    estado: "Inglaterra",
    cor1: "#E30613",
    cor2: "#FFFFFF",
    prestigio: 70,
    torcida: 25000000,
    estadio_cap: 17250,
    saldo: 160000000,
    file_key: "brentford",
    estadio_nome: "Gtech Community Stadium",
    patrocinador: "Hollywoodbets",
    escudo_url: getIntlEscudo("brentford"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Nottingham Forest",
    curto: "NFO",
    cidade: "Nottingham",
    estado: "Inglaterra",
    cor1: "#DD0000",
    cor2: "#FFFFFF",
    prestigio: 72,
    torcida: 50000000,
    estadio_cap: 30445,
    saldo: 180000000,
    file_key: "nottingham_forest",
    estadio_nome: "City Ground",
    patrocinador: "BOXT",
    escudo_url: getIntlEscudo("nottingham_forest"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Leicester City",
    curto: "LEI",
    cidade: "Leicester",
    estado: "Inglaterra",
    cor1: "#003090",
    cor2: "#FDBE11",
    prestigio: 75,
    torcida: 60000000,
    estadio_cap: 32261,
    saldo: 200000000,
    file_key: "leicester",
    estadio_nome: "King Power Stadium",
    patrocinador: "King Power",
    escudo_url: getIntlEscudo("leicester"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Ipswich Town",
    curto: "IPS",
    cidade: "Ipswich",
    estado: "Inglaterra",
    cor1: "#0033A0",
    cor2: "#FFFFFF",
    prestigio: 65,
    torcida: 20000000,
    estadio_cap: 30311,
    saldo: 100000000,
    file_key: "ipswich",
    estadio_nome: "Portman Road",
    patrocinador: "Ed Sheeran",
    escudo_url: getIntlEscudo("ipswich"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  },
  {
    nome: "Southampton",
    curto: "SOU",
    cidade: "Southampton",
    estado: "Inglaterra",
    cor1: "#D71920",
    cor2: "#130C0E",
    prestigio: 68,
    torcida: 35000000,
    estadio_cap: 32384,
    saldo: 120000000,
    file_key: "southampton",
    estadio_nome: "St Mary's Stadium",
    patrocinador: "Sportsbet.io",
    escudo_url: getIntlEscudo("southampton"),
    divisao: "premier_league",
    regiao: "europa",
    pais: "Inglaterra"
  }
]

// =============================================
// LA LIGA - ESPANHA
// =============================================
export const laLigaTeams: Team[] = [
  {
    nome: "Real Madrid",
    curto: "RMA",
    cidade: "Madrid",
    estado: "Espanha",
    cor1: "#FFFFFF",
    cor2: "#00529F",
    prestigio: 98,
    torcida: 800000000,
    estadio_cap: 81044,
    saldo: 900000000,
    file_key: "real_madrid",
    estadio_nome: "Santiago Bernabeu",
    patrocinador: "Emirates",
    escudo_url: getIntlEscudo("real_madrid"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Barcelona",
    curto: "BAR",
    cidade: "Barcelona",
    estado: "Espanha",
    cor1: "#004D98",
    cor2: "#A50044",
    prestigio: 95,
    torcida: 750000000,
    estadio_cap: 99354,
    saldo: 700000000,
    file_key: "barcelona",
    estadio_nome: "Spotify Camp Nou",
    patrocinador: "Spotify",
    escudo_url: getIntlEscudo("barcelona"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Atletico Madrid",
    curto: "ATM",
    cidade: "Madrid",
    estado: "Espanha",
    cor1: "#CB3524",
    cor2: "#FFFFFF",
    prestigio: 88,
    torcida: 300000000,
    estadio_cap: 70460,
    saldo: 500000000,
    file_key: "atletico_madrid",
    estadio_nome: "Civitas Metropolitano",
    patrocinador: "Riyadh Air",
    escudo_url: getIntlEscudo("atletico_madrid"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Athletic Bilbao",
    curto: "ATH",
    cidade: "Bilbao",
    estado: "Espanha",
    cor1: "#EE2523",
    cor2: "#FFFFFF",
    prestigio: 80,
    torcida: 100000000,
    estadio_cap: 53289,
    saldo: 280000000,
    file_key: "athletic_bilbao",
    estadio_nome: "San Mames",
    patrocinador: "Kutxabank",
    escudo_url: getIntlEscudo("athletic_bilbao"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Real Sociedad",
    curto: "RSO",
    cidade: "San Sebastian",
    estado: "Espanha",
    cor1: "#0067B1",
    cor2: "#FFFFFF",
    prestigio: 78,
    torcida: 80000000,
    estadio_cap: 39500,
    saldo: 250000000,
    file_key: "real_sociedad",
    estadio_nome: "Reale Arena",
    patrocinador: "Macron",
    escudo_url: getIntlEscudo("real_sociedad"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Villarreal",
    curto: "VIL",
    cidade: "Villarreal",
    estado: "Espanha",
    cor1: "#FFE500",
    cor2: "#005DAA",
    prestigio: 77,
    torcida: 60000000,
    estadio_cap: 23500,
    saldo: 220000000,
    file_key: "villarreal",
    estadio_nome: "Estadio de la Ceramica",
    patrocinador: "Pamesa",
    escudo_url: getIntlEscudo("villarreal"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Real Betis",
    curto: "BET",
    cidade: "Sevilha",
    estado: "Espanha",
    cor1: "#00954C",
    cor2: "#FFFFFF",
    prestigio: 76,
    torcida: 70000000,
    estadio_cap: 60721,
    saldo: 200000000,
    file_key: "real_betis",
    estadio_nome: "Benito Villamarin",
    patrocinador: "Thermomix",
    escudo_url: getIntlEscudo("real_betis"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Sevilla",
    curto: "SEV",
    cidade: "Sevilha",
    estado: "Espanha",
    cor1: "#FFFFFF",
    cor2: "#D10D11",
    prestigio: 79,
    torcida: 90000000,
    estadio_cap: 43883,
    saldo: 260000000,
    file_key: "sevilla",
    estadio_nome: "Ramon Sanchez-Pizjuan",
    patrocinador: "Castore",
    escudo_url: getIntlEscudo("sevilla"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Valencia",
    curto: "VAL",
    cidade: "Valencia",
    estado: "Espanha",
    cor1: "#FFFFFF",
    cor2: "#FF4F14",
    prestigio: 75,
    torcida: 80000000,
    estadio_cap: 55000,
    saldo: 180000000,
    file_key: "valencia",
    estadio_nome: "Mestalla",
    patrocinador: "Bwin",
    escudo_url: getIntlEscudo("valencia"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Girona",
    curto: "GIR",
    cidade: "Girona",
    estado: "Espanha",
    cor1: "#CD2534",
    cor2: "#FFFFFF",
    prestigio: 74,
    torcida: 30000000,
    estadio_cap: 14624,
    saldo: 150000000,
    file_key: "girona",
    estadio_nome: "Montilivi",
    patrocinador: "Eurostars",
    escudo_url: getIntlEscudo("girona"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Getafe",
    curto: "GET",
    cidade: "Getafe",
    estado: "Espanha",
    cor1: "#005999",
    cor2: "#FFFFFF",
    prestigio: 68,
    torcida: 20000000,
    estadio_cap: 17393,
    saldo: 80000000,
    file_key: "getafe",
    estadio_nome: "Coliseum Alfonso Perez",
    patrocinador: "Joma",
    escudo_url: getIntlEscudo("getafe"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Osasuna",
    curto: "OSA",
    cidade: "Pamplona",
    estado: "Espanha",
    cor1: "#D91A21",
    cor2: "#132257",
    prestigio: 67,
    torcida: 25000000,
    estadio_cap: 23576,
    saldo: 70000000,
    file_key: "osasuna",
    estadio_nome: "El Sadar",
    patrocinador: "Adidas",
    escudo_url: getIntlEscudo("osasuna"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Celta Vigo",
    curto: "CEL",
    cidade: "Vigo",
    estado: "Espanha",
    cor1: "#8AC3EE",
    cor2: "#FFFFFF",
    prestigio: 70,
    torcida: 35000000,
    estadio_cap: 29000,
    saldo: 100000000,
    file_key: "celta_vigo",
    estadio_nome: "Balaidos",
    patrocinador: "Adidas",
    escudo_url: getIntlEscudo("celta_vigo"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Rayo Vallecano",
    curto: "RAY",
    cidade: "Madrid",
    estado: "Espanha",
    cor1: "#E53027",
    cor2: "#FFFFFF",
    prestigio: 66,
    torcida: 20000000,
    estadio_cap: 14708,
    saldo: 60000000,
    file_key: "rayo_vallecano",
    estadio_nome: "Campo de Futbol de Vallecas",
    patrocinador: "Kelme",
    escudo_url: getIntlEscudo("rayo_vallecano"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Mallorca",
    curto: "MLL",
    cidade: "Palma",
    estado: "Espanha",
    cor1: "#E20613",
    cor2: "#000000",
    prestigio: 68,
    torcida: 25000000,
    estadio_cap: 23142,
    saldo: 80000000,
    file_key: "mallorca",
    estadio_nome: "Visit Mallorca Estadi",
    patrocinador: "Nike",
    escudo_url: getIntlEscudo("mallorca"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Las Palmas",
    curto: "LPA",
    cidade: "Las Palmas",
    estado: "Espanha",
    cor1: "#FFE400",
    cor2: "#0038A8",
    prestigio: 65,
    torcida: 20000000,
    estadio_cap: 32392,
    saldo: 50000000,
    file_key: "las_palmas",
    estadio_nome: "Gran Canaria",
    patrocinador: "Hummel",
    escudo_url: getIntlEscudo("las_palmas"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Alaves",
    curto: "ALA",
    cidade: "Vitoria",
    estado: "Espanha",
    cor1: "#003DA5",
    cor2: "#FFFFFF",
    prestigio: 64,
    torcida: 15000000,
    estadio_cap: 19840,
    saldo: 45000000,
    file_key: "alaves",
    estadio_nome: "Mendizorrotza",
    patrocinador: "Kelme",
    escudo_url: getIntlEscudo("alaves"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Leganes",
    curto: "LEG",
    cidade: "Leganes",
    estado: "Espanha",
    cor1: "#003DA5",
    cor2: "#FFFFFF",
    prestigio: 62,
    torcida: 10000000,
    estadio_cap: 12454,
    saldo: 35000000,
    file_key: "leganes",
    estadio_nome: "Butarque",
    patrocinador: "Joma",
    escudo_url: getIntlEscudo("leganes"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Espanyol",
    curto: "ESP",
    cidade: "Barcelona",
    estado: "Espanha",
    cor1: "#007FC8",
    cor2: "#FFFFFF",
    prestigio: 70,
    torcida: 40000000,
    estadio_cap: 40500,
    saldo: 90000000,
    file_key: "espanyol",
    estadio_nome: "RCDE Stadium",
    patrocinador: "Kelme",
    escudo_url: getIntlEscudo("espanyol"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  },
  {
    nome: "Valladolid",
    curto: "VLL",
    cidade: "Valladolid",
    estado: "Espanha",
    cor1: "#8B2B8B",
    cor2: "#FFFFFF",
    prestigio: 63,
    torcida: 15000000,
    estadio_cap: 27618,
    saldo: 40000000,
    file_key: "valladolid",
    estadio_nome: "Jose Zorrilla",
    patrocinador: "Kappa",
    escudo_url: getIntlEscudo("valladolid"),
    divisao: "la_liga",
    regiao: "europa",
    pais: "Espanha"
  }
]

// =============================================
// SERIE A - ITALIA
// =============================================
export const serieAItaTeams: Team[] = [
  {
    nome: "Inter",
    curto: "INT",
    cidade: "Milao",
    estado: "Italia",
    cor1: "#0068A8",
    cor2: "#000000",
    prestigio: 90,
    torcida: 350000000,
    estadio_cap: 75923,
    saldo: 550000000,
    file_key: "inter_milan",
    estadio_nome: "San Siro",
    patrocinador: "Paramount+",
    escudo_url: getIntlEscudo("inter_milan"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "AC Milan",
    curto: "MIL",
    cidade: "Milao",
    estado: "Italia",
    cor1: "#FB090B",
    cor2: "#000000",
    prestigio: 88,
    torcida: 400000000,
    estadio_cap: 75923,
    saldo: 500000000,
    file_key: "ac_milan",
    estadio_nome: "San Siro",
    patrocinador: "Emirates",
    escudo_url: getIntlEscudo("ac_milan"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Juventus",
    curto: "JUV",
    cidade: "Turim",
    estado: "Italia",
    cor1: "#000000",
    cor2: "#FFFFFF",
    prestigio: 87,
    torcida: 450000000,
    estadio_cap: 41507,
    saldo: 480000000,
    file_key: "juventus",
    estadio_nome: "Allianz Stadium",
    patrocinador: "Jeep",
    escudo_url: getIntlEscudo("juventus"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Napoli",
    curto: "NAP",
    cidade: "Napoles",
    estado: "Italia",
    cor1: "#12A0D7",
    cor2: "#FFFFFF",
    prestigio: 86,
    torcida: 200000000,
    estadio_cap: 54726,
    saldo: 400000000,
    file_key: "napoli",
    estadio_nome: "Diego Armando Maradona",
    patrocinador: "MSC",
    escudo_url: getIntlEscudo("napoli"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Roma",
    curto: "ROM",
    cidade: "Roma",
    estado: "Italia",
    cor1: "#8E1F2F",
    cor2: "#F0BC42",
    prestigio: 82,
    torcida: 250000000,
    estadio_cap: 72698,
    saldo: 320000000,
    file_key: "roma",
    estadio_nome: "Olimpico",
    patrocinador: "Riyadh Season",
    escudo_url: getIntlEscudo("roma"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Lazio",
    curto: "LAZ",
    cidade: "Roma",
    estado: "Italia",
    cor1: "#87D8F7",
    cor2: "#FFFFFF",
    prestigio: 78,
    torcida: 150000000,
    estadio_cap: 72698,
    saldo: 250000000,
    file_key: "lazio",
    estadio_nome: "Olimpico",
    patrocinador: "Binance",
    escudo_url: getIntlEscudo("lazio"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Atalanta",
    curto: "ATA",
    cidade: "Bergamo",
    estado: "Italia",
    cor1: "#1E71B8",
    cor2: "#000000",
    prestigio: 83,
    torcida: 80000000,
    estadio_cap: 24950,
    saldo: 350000000,
    file_key: "atalanta",
    estadio_nome: "Gewiss Stadium",
    patrocinador: "Radici",
    escudo_url: getIntlEscudo("atalanta"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Fiorentina",
    curto: "FIO",
    cidade: "Florenca",
    estado: "Italia",
    cor1: "#482B79",
    cor2: "#FFFFFF",
    prestigio: 77,
    torcida: 100000000,
    estadio_cap: 43147,
    saldo: 220000000,
    file_key: "fiorentina",
    estadio_nome: "Artemio Franchi",
    patrocinador: "Mediacom",
    escudo_url: getIntlEscudo("fiorentina"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Bologna",
    curto: "BOL",
    cidade: "Bolonha",
    estado: "Italia",
    cor1: "#1A2F48",
    cor2: "#A21E23",
    prestigio: 76,
    torcida: 70000000,
    estadio_cap: 38279,
    saldo: 200000000,
    file_key: "bologna",
    estadio_nome: "Renato Dall'Ara",
    patrocinador: "Macron",
    escudo_url: getIntlEscudo("bologna"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Torino",
    curto: "TOR",
    cidade: "Turim",
    estado: "Italia",
    cor1: "#8B0000",
    cor2: "#FFFFFF",
    prestigio: 72,
    torcida: 60000000,
    estadio_cap: 28177,
    saldo: 150000000,
    file_key: "torino",
    estadio_nome: "Olimpico Grande Torino",
    patrocinador: "Suzuki",
    escudo_url: getIntlEscudo("torino"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Udinese",
    curto: "UDI",
    cidade: "Udine",
    estado: "Italia",
    cor1: "#000000",
    cor2: "#FFFFFF",
    prestigio: 68,
    torcida: 30000000,
    estadio_cap: 25144,
    saldo: 100000000,
    file_key: "udinese",
    estadio_nome: "Friuli",
    patrocinador: "Macron",
    escudo_url: getIntlEscudo("udinese"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Genoa",
    curto: "GEN",
    cidade: "Genova",
    estado: "Italia",
    cor1: "#A61C32",
    cor2: "#15264A",
    prestigio: 70,
    torcida: 50000000,
    estadio_cap: 36599,
    saldo: 120000000,
    file_key: "genoa",
    estadio_nome: "Luigi Ferraris",
    patrocinador: "Kappa",
    escudo_url: getIntlEscudo("genoa"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Monza",
    curto: "MON",
    cidade: "Monza",
    estado: "Italia",
    cor1: "#FFFFFF",
    cor2: "#CE0E2D",
    prestigio: 65,
    torcida: 20000000,
    estadio_cap: 16917,
    saldo: 80000000,
    file_key: "monza",
    estadio_nome: "U-Power Stadium",
    patrocinador: "Lotto",
    escudo_url: getIntlEscudo("monza"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Hellas Verona",
    curto: "VER",
    cidade: "Verona",
    estado: "Italia",
    cor1: "#003D7F",
    cor2: "#FFD100",
    prestigio: 66,
    torcida: 25000000,
    estadio_cap: 39371,
    saldo: 70000000,
    file_key: "hellas_verona",
    estadio_nome: "Bentegodi",
    patrocinador: "Macron",
    escudo_url: getIntlEscudo("hellas_verona"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Cagliari",
    curto: "CAG",
    cidade: "Cagliari",
    estado: "Italia",
    cor1: "#A61C32",
    cor2: "#1E3C70",
    prestigio: 67,
    torcida: 30000000,
    estadio_cap: 16416,
    saldo: 80000000,
    file_key: "cagliari",
    estadio_nome: "Unipol Domus",
    patrocinador: "Eye Sport",
    escudo_url: getIntlEscudo("cagliari"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Empoli",
    curto: "EMP",
    cidade: "Empoli",
    estado: "Italia",
    cor1: "#005CA9",
    cor2: "#FFFFFF",
    prestigio: 63,
    torcida: 15000000,
    estadio_cap: 16284,
    saldo: 50000000,
    file_key: "empoli",
    estadio_nome: "Carlo Castellani",
    patrocinador: "Kappa",
    escudo_url: getIntlEscudo("empoli"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Como",
    curto: "COM",
    cidade: "Como",
    estado: "Italia",
    cor1: "#003DA5",
    cor2: "#FFFFFF",
    prestigio: 60,
    torcida: 10000000,
    estadio_cap: 13602,
    saldo: 40000000,
    file_key: "como",
    estadio_nome: "Giuseppe Sinigaglia",
    patrocinador: "Castore",
    escudo_url: getIntlEscudo("como"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Parma",
    curto: "PAR",
    cidade: "Parma",
    estado: "Italia",
    cor1: "#FFFF00",
    cor2: "#003DA5",
    prestigio: 68,
    torcida: 35000000,
    estadio_cap: 27906,
    saldo: 90000000,
    file_key: "parma",
    estadio_nome: "Ennio Tardini",
    patrocinador: "Erreà",
    escudo_url: getIntlEscudo("parma"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Lecce",
    curto: "LEC",
    cidade: "Lecce",
    estado: "Italia",
    cor1: "#FFFF00",
    cor2: "#E30613",
    prestigio: 62,
    torcida: 20000000,
    estadio_cap: 33876,
    saldo: 45000000,
    file_key: "lecce",
    estadio_nome: "Via del Mare",
    patrocinador: "Asics",
    escudo_url: getIntlEscudo("lecce"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  },
  {
    nome: "Venezia",
    curto: "VEN",
    cidade: "Veneza",
    estado: "Italia",
    cor1: "#FF6600",
    cor2: "#004D26",
    prestigio: 61,
    torcida: 15000000,
    estadio_cap: 11150,
    saldo: 35000000,
    file_key: "venezia",
    estadio_nome: "Pier Luigi Penzo",
    patrocinador: "Kappa",
    escudo_url: getIntlEscudo("venezia"),
    divisao: "serie_a_ita",
    regiao: "europa",
    pais: "Italia"
  }
]

// =============================================
// BUNDESLIGA - ALEMANHA
// =============================================
export const bundesligaTeams: Team[] = [
  {
    nome: "Bayern Munich",
    curto: "BAY",
    cidade: "Munique",
    estado: "Alemanha",
    cor1: "#DC052D",
    cor2: "#FFFFFF",
    prestigio: 94,
    torcida: 500000000,
    estadio_cap: 75024,
    saldo: 750000000,
    file_key: "bayern_munich",
    estadio_nome: "Allianz Arena",
    patrocinador: "T-Mobile",
    escudo_url: getIntlEscudo("bayern_munich"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Borussia Dortmund",
    curto: "BVB",
    cidade: "Dortmund",
    estado: "Alemanha",
    cor1: "#FDE100",
    cor2: "#000000",
    prestigio: 88,
    torcida: 300000000,
    estadio_cap: 81365,
    saldo: 450000000,
    file_key: "borussia_dortmund",
    estadio_nome: "Signal Iduna Park",
    patrocinador: "1&1",
    escudo_url: getIntlEscudo("borussia_dortmund"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "RB Leipzig",
    curto: "RBL",
    cidade: "Leipzig",
    estado: "Alemanha",
    cor1: "#DD0741",
    cor2: "#FFFFFF",
    prestigio: 84,
    torcida: 100000000,
    estadio_cap: 47069,
    saldo: 400000000,
    file_key: "rb_leipzig",
    estadio_nome: "Red Bull Arena",
    patrocinador: "Red Bull",
    escudo_url: getIntlEscudo("rb_leipzig"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Bayer Leverkusen",
    curto: "LEV",
    cidade: "Leverkusen",
    estado: "Alemanha",
    cor1: "#E32221",
    cor2: "#000000",
    prestigio: 86,
    torcida: 120000000,
    estadio_cap: 30210,
    saldo: 420000000,
    file_key: "bayer_leverkusen",
    estadio_nome: "BayArena",
    patrocinador: "Bayer",
    escudo_url: getIntlEscudo("bayer_leverkusen"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Eintracht Frankfurt",
    curto: "SGE",
    cidade: "Frankfurt",
    estado: "Alemanha",
    cor1: "#E1000F",
    cor2: "#000000",
    prestigio: 78,
    torcida: 80000000,
    estadio_cap: 51500,
    saldo: 280000000,
    file_key: "eintracht_frankfurt",
    estadio_nome: "Deutsche Bank Park",
    patrocinador: "Indeed",
    escudo_url: getIntlEscudo("eintracht_frankfurt"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Wolfsburg",
    curto: "WOB",
    cidade: "Wolfsburg",
    estado: "Alemanha",
    cor1: "#65B32E",
    cor2: "#FFFFFF",
    prestigio: 74,
    torcida: 40000000,
    estadio_cap: 30000,
    saldo: 200000000,
    file_key: "wolfsburg",
    estadio_nome: "Volkswagen Arena",
    patrocinador: "VW",
    escudo_url: getIntlEscudo("wolfsburg"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Borussia Monchengladbach",
    curto: "BMG",
    cidade: "Monchengladbach",
    estado: "Alemanha",
    cor1: "#000000",
    cor2: "#FFFFFF",
    prestigio: 75,
    torcida: 60000000,
    estadio_cap: 54057,
    saldo: 220000000,
    file_key: "borussia_mgladbach",
    estadio_nome: "Borussia-Park",
    patrocinador: "Postbank",
    escudo_url: getIntlEscudo("borussia_mgladbach"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Freiburg",
    curto: "SCF",
    cidade: "Freiburg",
    estado: "Alemanha",
    cor1: "#000000",
    cor2: "#E2001A",
    prestigio: 76,
    torcida: 50000000,
    estadio_cap: 34700,
    saldo: 180000000,
    file_key: "freiburg",
    estadio_nome: "Europa-Park Stadion",
    patrocinador: "Schwarzwaldmilch",
    escudo_url: getIntlEscudo("freiburg"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Stuttgart",
    curto: "VFB",
    cidade: "Stuttgart",
    estado: "Alemanha",
    cor1: "#E32219",
    cor2: "#FFFFFF",
    prestigio: 77,
    torcida: 70000000,
    estadio_cap: 60449,
    saldo: 250000000,
    file_key: "stuttgart",
    estadio_nome: "MHPArena",
    patrocinador: "Mercedes-Benz",
    escudo_url: getIntlEscudo("stuttgart"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Union Berlin",
    curto: "UNB",
    cidade: "Berlim",
    estado: "Alemanha",
    cor1: "#EB1923",
    cor2: "#FFFFFF",
    prestigio: 73,
    torcida: 45000000,
    estadio_cap: 22012,
    saldo: 150000000,
    file_key: "union_berlin",
    estadio_nome: "Stadion An der Alten Forsterei",
    patrocinador: "Aroundtown",
    escudo_url: getIntlEscudo("union_berlin"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Hoffenheim",
    curto: "TSG",
    cidade: "Sinsheim",
    estado: "Alemanha",
    cor1: "#1961B5",
    cor2: "#FFFFFF",
    prestigio: 72,
    torcida: 30000000,
    estadio_cap: 30150,
    saldo: 160000000,
    file_key: "hoffenheim",
    estadio_nome: "PreZero Arena",
    patrocinador: "SAP",
    escudo_url: getIntlEscudo("hoffenheim"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Mainz 05",
    curto: "M05",
    cidade: "Mainz",
    estado: "Alemanha",
    cor1: "#C3141E",
    cor2: "#FFFFFF",
    prestigio: 68,
    torcida: 25000000,
    estadio_cap: 33305,
    saldo: 100000000,
    file_key: "mainz",
    estadio_nome: "Mewa Arena",
    patrocinador: "Kömmerling",
    escudo_url: getIntlEscudo("mainz"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Werder Bremen",
    curto: "SVW",
    cidade: "Bremen",
    estado: "Alemanha",
    cor1: "#1D9053",
    cor2: "#FFFFFF",
    prestigio: 72,
    torcida: 55000000,
    estadio_cap: 42100,
    saldo: 140000000,
    file_key: "werder_bremen",
    estadio_nome: "Weserstadion",
    patrocinador: "Wiesenhof",
    escudo_url: getIntlEscudo("werder_bremen"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Augsburg",
    curto: "FCA",
    cidade: "Augsburg",
    estado: "Alemanha",
    cor1: "#BA3733",
    cor2: "#FFFFFF",
    prestigio: 66,
    torcida: 20000000,
    estadio_cap: 30660,
    saldo: 80000000,
    file_key: "augsburg",
    estadio_nome: "WWK Arena",
    patrocinador: "WWK",
    escudo_url: getIntlEscudo("augsburg"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Bochum",
    curto: "BOC",
    cidade: "Bochum",
    estado: "Alemanha",
    cor1: "#005CA9",
    cor2: "#FFFFFF",
    prestigio: 64,
    torcida: 20000000,
    estadio_cap: 27599,
    saldo: 60000000,
    file_key: "bochum",
    estadio_nome: "Vonovia Ruhrstadion",
    patrocinador: "Vonovia",
    escudo_url: getIntlEscudo("bochum"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Heidenheim",
    curto: "HDH",
    cidade: "Heidenheim",
    estado: "Alemanha",
    cor1: "#E30613",
    cor2: "#005CA9",
    prestigio: 62,
    torcida: 10000000,
    estadio_cap: 15000,
    saldo: 45000000,
    file_key: "heidenheim",
    estadio_nome: "Voith-Arena",
    patrocinador: "Voith",
    escudo_url: getIntlEscudo("heidenheim"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "St. Pauli",
    curto: "STP",
    cidade: "Hamburgo",
    estado: "Alemanha",
    cor1: "#8B4513",
    cor2: "#FFFFFF",
    prestigio: 65,
    torcida: 30000000,
    estadio_cap: 29546,
    saldo: 50000000,
    file_key: "st_pauli",
    estadio_nome: "Millerntor-Stadion",
    patrocinador: "Congstar",
    escudo_url: getIntlEscudo("st_pauli"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  },
  {
    nome: "Holstein Kiel",
    curto: "KIE",
    cidade: "Kiel",
    estado: "Alemanha",
    cor1: "#003DA5",
    cor2: "#E30613",
    prestigio: 58,
    torcida: 8000000,
    estadio_cap: 15034,
    saldo: 30000000,
    file_key: "holstein_kiel",
    estadio_nome: "Holstein-Stadion",
    patrocinador: "EWE",
    escudo_url: getIntlEscudo("holstein_kiel"),
    divisao: "bundesliga",
    regiao: "europa",
    pais: "Alemanha"
  }
]

// =============================================
// LIGUE 1 - FRANCA
// =============================================
export const ligue1Teams: Team[] = [
  {
    nome: "Paris Saint-Germain",
    curto: "PSG",
    cidade: "Paris",
    estado: "Franca",
    cor1: "#004170",
    cor2: "#DA291C",
    prestigio: 93,
    torcida: 400000000,
    estadio_cap: 47929,
    saldo: 700000000,
    file_key: "psg",
    estadio_nome: "Parc des Princes",
    patrocinador: "Qatar Airways",
    escudo_url: getIntlEscudo("psg"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Monaco",
    curto: "MON",
    cidade: "Monaco",
    estado: "Monaco",
    cor1: "#E30613",
    cor2: "#FFFFFF",
    prestigio: 82,
    torcida: 80000000,
    estadio_cap: 18523,
    saldo: 350000000,
    file_key: "monaco",
    estadio_nome: "Stade Louis II",
    patrocinador: "Fedcom",
    escudo_url: getIntlEscudo("monaco"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Marseille",
    curto: "OM",
    cidade: "Marselha",
    estado: "Franca",
    cor1: "#2FAEE0",
    cor2: "#FFFFFF",
    prestigio: 80,
    torcida: 150000000,
    estadio_cap: 67394,
    saldo: 280000000,
    file_key: "marseille",
    estadio_nome: "Velodrome",
    patrocinador: "CMA CGM",
    escudo_url: getIntlEscudo("marseille"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Lille",
    curto: "LIL",
    cidade: "Lille",
    estado: "Franca",
    cor1: "#E30613",
    cor2: "#0033A0",
    prestigio: 78,
    torcida: 60000000,
    estadio_cap: 50186,
    saldo: 250000000,
    file_key: "lille",
    estadio_nome: "Stade Pierre-Mauroy",
    patrocinador: "Decathlon",
    escudo_url: getIntlEscudo("lille"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Lyon",
    curto: "OL",
    cidade: "Lyon",
    estado: "Franca",
    cor1: "#0033A0",
    cor2: "#FFFFFF",
    prestigio: 77,
    torcida: 100000000,
    estadio_cap: 59186,
    saldo: 220000000,
    file_key: "lyon",
    estadio_nome: "Groupama Stadium",
    patrocinador: "Groupama",
    escudo_url: getIntlEscudo("lyon"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Nice",
    curto: "OGC",
    cidade: "Nice",
    estado: "Franca",
    cor1: "#E30613",
    cor2: "#000000",
    prestigio: 74,
    torcida: 40000000,
    estadio_cap: 35624,
    saldo: 180000000,
    file_key: "nice",
    estadio_nome: "Allianz Riviera",
    patrocinador: "Ineos",
    escudo_url: getIntlEscudo("nice"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Lens",
    curto: "RCL",
    cidade: "Lens",
    estado: "Franca",
    cor1: "#FFD700",
    cor2: "#E30613",
    prestigio: 75,
    torcida: 50000000,
    estadio_cap: 38223,
    saldo: 160000000,
    file_key: "lens",
    estadio_nome: "Stade Bollaert-Delelis",
    patrocinador: "Centrakor",
    escudo_url: getIntlEscudo("lens"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Rennes",
    curto: "SRF",
    cidade: "Rennes",
    estado: "Franca",
    cor1: "#E30613",
    cor2: "#000000",
    prestigio: 73,
    torcida: 35000000,
    estadio_cap: 29778,
    saldo: 150000000,
    file_key: "rennes",
    estadio_nome: "Roazhon Park",
    patrocinador: "Samsic",
    escudo_url: getIntlEscudo("rennes"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Brest",
    curto: "SB29",
    cidade: "Brest",
    estado: "Franca",
    cor1: "#E30613",
    cor2: "#FFFFFF",
    prestigio: 70,
    torcida: 20000000,
    estadio_cap: 15220,
    saldo: 100000000,
    file_key: "brest",
    estadio_nome: "Stade Francis-Le Ble",
    patrocinador: "Arkea",
    escudo_url: getIntlEscudo("brest"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Strasbourg",
    curto: "RCS",
    cidade: "Estrasburgo",
    estado: "Franca",
    cor1: "#0055A4",
    cor2: "#FFFFFF",
    prestigio: 68,
    torcida: 25000000,
    estadio_cap: 26109,
    saldo: 80000000,
    file_key: "strasbourg",
    estadio_nome: "Stade de la Meinau",
    patrocinador: "RCPowerBall",
    escudo_url: getIntlEscudo("strasbourg"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Nantes",
    curto: "FCN",
    cidade: "Nantes",
    estado: "Franca",
    cor1: "#FCDD09",
    cor2: "#0F9D58",
    prestigio: 70,
    torcida: 40000000,
    estadio_cap: 37473,
    saldo: 100000000,
    file_key: "nantes",
    estadio_nome: "Stade de la Beaujoire",
    patrocinador: "Synergie",
    escudo_url: getIntlEscudo("nantes"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Reims",
    curto: "SDR",
    cidade: "Reims",
    estado: "Franca",
    cor1: "#E30613",
    cor2: "#FFFFFF",
    prestigio: 66,
    torcida: 20000000,
    estadio_cap: 21684,
    saldo: 70000000,
    file_key: "reims",
    estadio_nome: "Stade Auguste-Delaune",
    patrocinador: "Mc Donald's",
    escudo_url: getIntlEscudo("reims"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Toulouse",
    curto: "TFC",
    cidade: "Toulouse",
    estado: "Franca",
    cor1: "#7B2C8D",
    cor2: "#FFFFFF",
    prestigio: 68,
    torcida: 25000000,
    estadio_cap: 33150,
    saldo: 80000000,
    file_key: "toulouse",
    estadio_nome: "Stadium de Toulouse",
    patrocinador: "Fiducial",
    escudo_url: getIntlEscudo("toulouse"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Montpellier",
    curto: "MHS",
    cidade: "Montpellier",
    estado: "Franca",
    cor1: "#003DA5",
    cor2: "#FF7F00",
    prestigio: 67,
    torcida: 22000000,
    estadio_cap: 32939,
    saldo: 75000000,
    file_key: "montpellier",
    estadio_nome: "Stade de la Mosson",
    patrocinador: "Unibet",
    escudo_url: getIntlEscudo("montpellier"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Le Havre",
    curto: "HAC",
    cidade: "Le Havre",
    estado: "Franca",
    cor1: "#6AADE4",
    cor2: "#FFFFFF",
    prestigio: 62,
    torcida: 12000000,
    estadio_cap: 25178,
    saldo: 40000000,
    file_key: "le_havre",
    estadio_nome: "Stade Oceane",
    patrocinador: "Zebet",
    escudo_url: getIntlEscudo("le_havre"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Auxerre",
    curto: "AJA",
    cidade: "Auxerre",
    estado: "Franca",
    cor1: "#005CA9",
    cor2: "#FFFFFF",
    prestigio: 65,
    torcida: 15000000,
    estadio_cap: 21500,
    saldo: 50000000,
    file_key: "auxerre",
    estadio_nome: "Stade de l'Abbe-Deschamps",
    patrocinador: "Winamax",
    escudo_url: getIntlEscudo("auxerre"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Angers",
    curto: "SCO",
    cidade: "Angers",
    estado: "Franca",
    cor1: "#000000",
    cor2: "#FFFFFF",
    prestigio: 63,
    torcida: 12000000,
    estadio_cap: 17835,
    saldo: 45000000,
    file_key: "angers",
    estadio_nome: "Stade Raymond Kopa",
    patrocinador: "Winamax",
    escudo_url: getIntlEscudo("angers"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  },
  {
    nome: "Saint-Etienne",
    curto: "ASSE",
    cidade: "Saint-Etienne",
    estado: "Franca",
    cor1: "#0F9D58",
    cor2: "#FFFFFF",
    prestigio: 70,
    torcida: 50000000,
    estadio_cap: 42000,
    saldo: 90000000,
    file_key: "saint_etienne",
    estadio_nome: "Stade Geoffroy-Guichard",
    patrocinador: "Abritel",
    escudo_url: getIntlEscudo("saint_etienne"),
    divisao: "ligue_1",
    regiao: "europa",
    pais: "Franca"
  }
]

// =============================================
// SAUDI PRO LEAGUE - ARABIA SAUDITA
// =============================================
export const saudiProTeams: Team[] = [
  {
    nome: "Al-Nassr",
    curto: "NAS",
    cidade: "Riade",
    estado: "Arabia Saudita",
    cor1: "#FFCC00",
    cor2: "#003DA5",
    prestigio: 85,
    torcida: 200000000,
    estadio_cap: 25000,
    saldo: 600000000,
    file_key: "al_nassr",
    estadio_nome: "Al-Awwal Park",
    patrocinador: "Saudi Tourism",
    escudo_url: getIntlEscudo("al_nassr"),
    divisao: "saudi_pro",
    regiao: "asia",
    pais: "Arabia Saudita"
  },
  {
    nome: "Al-Hilal",
    curto: "HIL",
    cidade: "Riade",
    estado: "Arabia Saudita",
    cor1: "#003DA5",
    cor2: "#FFFFFF",
    prestigio: 88,
    torcida: 250000000,
    estadio_cap: 67000,
    saldo: 700000000,
    file_key: "al_hilal",
    estadio_nome: "Kingdom Arena",
    patrocinador: "Mobily",
    escudo_url: getIntlEscudo("al_hilal"),
    divisao: "saudi_pro",
    regiao: "asia",
    pais: "Arabia Saudita"
  },
  {
    nome: "Al-Ittihad",
    curto: "ITT",
    cidade: "Jeddah",
    estado: "Arabia Saudita",
    cor1: "#FFCC00",
    cor2: "#000000",
    prestigio: 84,
    torcida: 180000000,
    estadio_cap: 62345,
    saldo: 550000000,
    file_key: "al_ittihad",
    estadio_nome: "King Abdullah Sports City",
    patrocinador: "SAUDIA",
    escudo_url: getIntlEscudo("al_ittihad"),
    divisao: "saudi_pro",
    regiao: "asia",
    pais: "Arabia Saudita"
  },
  {
    nome: "Al-Ahli",
    curto: "AHL",
    cidade: "Jeddah",
    estado: "Arabia Saudita",
    cor1: "#0F9D58",
    cor2: "#FFFFFF",
    prestigio: 82,
    torcida: 150000000,
    estadio_cap: 62345,
    saldo: 500000000,
    file_key: "al_ahli_saudi",
    estadio_nome: "King Abdullah Sports City",
    patrocinador: "Nestle",
    escudo_url: getIntlEscudo("al_ahli_saudi"),
    divisao: "saudi_pro",
    regiao: "asia",
    pais: "Arabia Saudita"
  },
  {
    nome: "Al-Shabab",
    curto: "SHA",
    cidade: "Riade",
    estado: "Arabia Saudita",
    cor1: "#FFFFFF",
    cor2: "#000000",
    prestigio: 75,
    torcida: 80000000,
    estadio_cap: 25000,
    saldo: 300000000,
    file_key: "al_shabab",
    estadio_nome: "Prince Faisal bin Fahd Stadium",
    patrocinador: "Riyad Bank",
    escudo_url: getIntlEscudo("al_shabab"),
    divisao: "saudi_pro",
    regiao: "asia",
    pais: "Arabia Saudita"
  },
  {
    nome: "Al-Ettifaq",
    curto: "ETT",
    cidade: "Dammam",
    estado: "Arabia Saudita",
    cor1: "#0F9D58",
    cor2: "#FFD700",
    prestigio: 73,
    torcida: 50000000,
    estadio_cap: 22000,
    saldo: 250000000,
    file_key: "al_ettifaq",
    estadio_nome: "Prince Mohamed bin Fahd Stadium",
    patrocinador: "SABIC",
    escudo_url: getIntlEscudo("al_ettifaq"),
    divisao: "saudi_pro",
    regiao: "asia",
    pais: "Arabia Saudita"
  },
  {
    nome: "Al-Taawoun",
    curto: "TAA",
    cidade: "Buraidah",
    estado: "Arabia Saudita",
    cor1: "#FFD700",
    cor2: "#003DA5",
    prestigio: 68,
    torcida: 30000000,
    estadio_cap: 25000,
    saldo: 150000000,
    file_key: "al_taawoun",
    estadio_nome: "King Abdullah Sport City Stadium",
    patrocinador: "STC",
    escudo_url: getIntlEscudo("al_taawoun"),
    divisao: "saudi_pro",
    regiao: "asia",
    pais: "Arabia Saudita"
  },
  {
    nome: "Al-Fateh",
    curto: "FAT",
    cidade: "Al-Hasa",
    estado: "Arabia Saudita",
    cor1: "#0F9D58",
    cor2: "#FFFFFF",
    prestigio: 65,
    torcida: 20000000,
    estadio_cap: 20000,
    saldo: 100000000,
    file_key: "al_fateh",
    estadio_nome: "Prince Abdullah bin Jalawi Stadium",
    patrocinador: "Aramco",
    escudo_url: getIntlEscudo("al_fateh"),
    divisao: "saudi_pro",
    regiao: "asia",
    pais: "Arabia Saudita"
  },
  {
    nome: "Al-Fayha",
    curto: "FAY",
    cidade: "Al-Majma'ah",
    estado: "Arabia Saudita",
    cor1: "#E30613",
    cor2: "#FFFFFF",
    prestigio: 62,
    torcida: 15000000,
    estadio_cap: 7000,
    saldo: 80000000,
    file_key: "al_fayha",
    estadio_nome: "Al-Majma'ah Sports City Stadium",
    patrocinador: "Al Rajhi Bank",
    escudo_url: getIntlEscudo("al_fayha"),
    divisao: "saudi_pro",
    regiao: "asia",
    pais: "Arabia Saudita"
  },
  {
    nome: "Al-Raed",
    curto: "RAE",
    cidade: "Buraidah",
    estado: "Arabia Saudita",
    cor1: "#E30613",
    cor2: "#000000",
    prestigio: 60,
    torcida: 12000000,
    estadio_cap: 25000,
    saldo: 60000000,
    file_key: "al_raed",
    estadio_nome: "King Abdullah Sport City Stadium",
    patrocinador: "Mobily",
    escudo_url: getIntlEscudo("al_raed"),
    divisao: "saudi_pro",
    regiao: "asia",
    pais: "Arabia Saudita"
  }
]

// =============================================
// MLS - ESTADOS UNIDOS
// =============================================
export const mlsTeams: Team[] = [
  {
    nome: "Inter Miami",
    curto: "MIA",
    cidade: "Miami",
    estado: "Florida",
    cor1: "#F5B5C8",
    cor2: "#231F20",
    prestigio: 85,
    torcida: 200000000,
    estadio_cap: 21550,
    saldo: 400000000,
    file_key: "inter_miami",
    estadio_nome: "Chase Stadium",
    patrocinador: "Royal Caribbean",
    escudo_url: getIntlEscudo("inter_miami"),
    divisao: "mls",
    regiao: "americas",
    pais: "Estados Unidos"
  },
  {
    nome: "LA Galaxy",
    curto: "LAG",
    cidade: "Los Angeles",
    estado: "California",
    cor1: "#00245D",
    cor2: "#FFD200",
    prestigio: 80,
    torcida: 100000000,
    estadio_cap: 27000,
    saldo: 300000000,
    file_key: "la_galaxy",
    estadio_nome: "Dignity Health Sports Park",
    patrocinador: "Herbalife",
    escudo_url: getIntlEscudo("la_galaxy"),
    divisao: "mls",
    regiao: "americas",
    pais: "Estados Unidos"
  },
  {
    nome: "LAFC",
    curto: "LAF",
    cidade: "Los Angeles",
    estado: "California",
    cor1: "#000000",
    cor2: "#C39E6D",
    prestigio: 82,
    torcida: 80000000,
    estadio_cap: 22000,
    saldo: 320000000,
    file_key: "lafc",
    estadio_nome: "BMO Stadium",
    patrocinador: "BMO",
    escudo_url: getIntlEscudo("lafc"),
    divisao: "mls",
    regiao: "americas",
    pais: "Estados Unidos"
  },
  {
    nome: "Atlanta United",
    curto: "ATL",
    cidade: "Atlanta",
    estado: "Georgia",
    cor1: "#80000A",
    cor2: "#231F20",
    prestigio: 78,
    torcida: 70000000,
    estadio_cap: 42500,
    saldo: 280000000,
    file_key: "atlanta_united",
    estadio_nome: "Mercedes-Benz Stadium",
    patrocinador: "American Family Insurance",
    escudo_url: getIntlEscudo("atlanta_united"),
    divisao: "mls",
    regiao: "americas",
    pais: "Estados Unidos"
  },
  {
    nome: "Seattle Sounders",
    curto: "SEA",
    cidade: "Seattle",
    estado: "Washington",
    cor1: "#5D9741",
    cor2: "#005595",
    prestigio: 77,
    torcida: 60000000,
    estadio_cap: 37722,
    saldo: 250000000,
    file_key: "seattle_sounders",
    estadio_nome: "Lumen Field",
    patrocinador: "Zulily",
    escudo_url: getIntlEscudo("seattle_sounders"),
    divisao: "mls",
    regiao: "americas",
    pais: "Estados Unidos"
  },
  {
    nome: "New York Red Bulls",
    curto: "NYR",
    cidade: "Nova York",
    estado: "New Jersey",
    cor1: "#E20613",
    cor2: "#FFCC00",
    prestigio: 73,
    torcida: 50000000,
    estadio_cap: 25000,
    saldo: 200000000,
    file_key: "ny_red_bulls",
    estadio_nome: "Red Bull Arena",
    patrocinador: "Red Bull",
    escudo_url: getIntlEscudo("ny_red_bulls"),
    divisao: "mls",
    regiao: "americas",
    pais: "Estados Unidos"
  },
  {
    nome: "NYCFC",
    curto: "NYC",
    cidade: "Nova York",
    estado: "Nova York",
    cor1: "#6CACE4",
    cor2: "#F15523",
    prestigio: 74,
    torcida: 45000000,
    estadio_cap: 25000,
    saldo: 220000000,
    file_key: "nycfc",
    estadio_nome: "Yankee Stadium",
    patrocinador: "Etihad Airways",
    escudo_url: getIntlEscudo("nycfc"),
    divisao: "mls",
    regiao: "americas",
    pais: "Estados Unidos"
  },
  {
    nome: "Columbus Crew",
    curto: "CLB",
    cidade: "Columbus",
    estado: "Ohio",
    cor1: "#000000",
    cor2: "#FEDD00",
    prestigio: 76,
    torcida: 40000000,
    estadio_cap: 20371,
    saldo: 200000000,
    file_key: "columbus_crew",
    estadio_nome: "Lower.com Field",
    patrocinador: "Lower.com",
    escudo_url: getIntlEscudo("columbus_crew"),
    divisao: "mls",
    regiao: "americas",
    pais: "Estados Unidos"
  },
  {
    nome: "FC Cincinnati",
    curto: "CIN",
    cidade: "Cincinnati",
    estado: "Ohio",
    cor1: "#F05323",
    cor2: "#263B80",
    prestigio: 72,
    torcida: 35000000,
    estadio_cap: 26000,
    saldo: 180000000,
    file_key: "fc_cincinnati",
    estadio_nome: "TQL Stadium",
    patrocinador: "Mercy Health",
    escudo_url: getIntlEscudo("fc_cincinnati"),
    divisao: "mls",
    regiao: "americas",
    pais: "Estados Unidos"
  },
  {
    nome: "Philadelphia Union",
    curto: "PHI",
    cidade: "Philadelphia",
    estado: "Pennsylvania",
    cor1: "#071B2C",
    cor2: "#B19B69",
    prestigio: 70,
    torcida: 30000000,
    estadio_cap: 18500,
    saldo: 150000000,
    file_key: "philadelphia_union",
    estadio_nome: "Subaru Park",
    patrocinador: "Bimbo",
    escudo_url: getIntlEscudo("philadelphia_union"),
    divisao: "mls",
    regiao: "americas",
    pais: "Estados Unidos"
  }
]

// =============================================
// LIGA MX - MEXICO
// =============================================
export const ligaMXTeams: Team[] = [
  {
    nome: "Club America",
    curto: "AME",
    cidade: "Cidade do Mexico",
    estado: "Mexico",
    cor1: "#FFCC00",
    cor2: "#003DA5",
    prestigio: 85,
    torcida: 150000000,
    estadio_cap: 87523,
    saldo: 350000000,
    file_key: "club_america",
    estadio_nome: "Estadio Azteca",
    patrocinador: "Caliente",
    escudo_url: getIntlEscudo("club_america"),
    divisao: "liga_mx",
    regiao: "americas",
    pais: "Mexico"
  },
  {
    nome: "Chivas Guadalajara",
    curto: "CHI",
    cidade: "Guadalajara",
    estado: "Mexico",
    cor1: "#E30613",
    cor2: "#FFFFFF",
    prestigio: 83,
    torcida: 140000000,
    estadio_cap: 49850,
    saldo: 300000000,
    file_key: "chivas",
    estadio_nome: "Estadio Akron",
    patrocinador: "Caliente",
    escudo_url: getIntlEscudo("chivas"),
    divisao: "liga_mx",
    regiao: "americas",
    pais: "Mexico"
  },
  {
    nome: "Cruz Azul",
    curto: "CAZ",
    cidade: "Cidade do Mexico",
    estado: "Mexico",
    cor1: "#003DA5",
    cor2: "#FFFFFF",
    prestigio: 80,
    torcida: 100000000,
    estadio_cap: 35161,
    saldo: 250000000,
    file_key: "cruz_azul",
    estadio_nome: "Estadio Azul",
    patrocinador: "CEMEX",
    escudo_url: getIntlEscudo("cruz_azul"),
    divisao: "liga_mx",
    regiao: "americas",
    pais: "Mexico"
  },
  {
    nome: "Tigres UANL",
    curto: "TIG",
    cidade: "Monterrey",
    estado: "Mexico",
    cor1: "#FFCC00",
    cor2: "#003DA5",
    prestigio: 84,
    torcida: 90000000,
    estadio_cap: 42000,
    saldo: 280000000,
    file_key: "tigres",
    estadio_nome: "Estadio Universitario",
    patrocinador: "CEMEX",
    escudo_url: getIntlEscudo("tigres"),
    divisao: "liga_mx",
    regiao: "americas",
    pais: "Mexico"
  },
  {
    nome: "Monterrey",
    curto: "MTY",
    cidade: "Monterrey",
    estado: "Mexico",
    cor1: "#003DA5",
    cor2: "#FFFFFF",
    prestigio: 82,
    torcida: 80000000,
    estadio_cap: 53500,
    saldo: 260000000,
    file_key: "monterrey",
    estadio_nome: "BBVA Stadium",
    patrocinador: "BBVA",
    escudo_url: getIntlEscudo("monterrey"),
    divisao: "liga_mx",
    regiao: "americas",
    pais: "Mexico"
  },
  {
    nome: "Pumas UNAM",
    curto: "PUM",
    cidade: "Cidade do Mexico",
    estado: "Mexico",
    cor1: "#003DA5",
    cor2: "#C39E6D",
    prestigio: 78,
    torcida: 70000000,
    estadio_cap: 62000,
    saldo: 200000000,
    file_key: "pumas",
    estadio_nome: "Estadio Olimpico Universitario",
    patrocinador: "Nike",
    escudo_url: getIntlEscudo("pumas"),
    divisao: "liga_mx",
    regiao: "americas",
    pais: "Mexico"
  },
  {
    nome: "Santos Laguna",
    curto: "SLA",
    cidade: "Torreon",
    estado: "Mexico",
    cor1: "#0F9D58",
    cor2: "#FFFFFF",
    prestigio: 75,
    torcida: 50000000,
    estadio_cap: 30168,
    saldo: 180000000,
    file_key: "santos_laguna",
    estadio_nome: "Estadio Corona",
    patrocinador: "Corona",
    escudo_url: getIntlEscudo("santos_laguna"),
    divisao: "liga_mx",
    regiao: "americas",
    pais: "Mexico"
  },
  {
    nome: "Toluca",
    curto: "TOL",
    cidade: "Toluca",
    estado: "Mexico",
    cor1: "#E30613",
    cor2: "#FFFFFF",
    prestigio: 76,
    torcida: 45000000,
    estadio_cap: 30000,
    saldo: 170000000,
    file_key: "toluca",
    estadio_nome: "Estadio Nemesio Diez",
    patrocinador: "Caliente",
    escudo_url: getIntlEscudo("toluca"),
    divisao: "liga_mx",
    regiao: "americas",
    pais: "Mexico"
  },
  {
    nome: "Leon",
    curto: "LEO",
    cidade: "Leon",
    estado: "Mexico",
    cor1: "#0F9D58",
    cor2: "#FFFFFF",
    prestigio: 74,
    torcida: 40000000,
    estadio_cap: 30900,
    saldo: 160000000,
    file_key: "leon",
    estadio_nome: "Estadio Leon",
    patrocinador: "Pirma",
    escudo_url: getIntlEscudo("leon"),
    divisao: "liga_mx",
    regiao: "americas",
    pais: "Mexico"
  },
  {
    nome: "Pachuca",
    curto: "PAC",
    cidade: "Pachuca",
    estado: "Mexico",
    cor1: "#005CA9",
    cor2: "#FFFFFF",
    prestigio: 77,
    torcida: 35000000,
    estadio_cap: 30000,
    saldo: 180000000,
    file_key: "pachuca",
    estadio_nome: "Estadio Hidalgo",
    patrocinador: "Charly",
    escudo_url: getIntlEscudo("pachuca"),
    divisao: "liga_mx",
    regiao: "americas",
    pais: "Mexico"
  }
]

// =============================================
// PRIMEIRA LIGA - PORTUGAL
// =============================================
export const primeiraLigaTeams: Team[] = [
  {
    nome: "Benfica",
    curto: "BEN",
    cidade: "Lisboa",
    estado: "Portugal",
    cor1: "#E30613",
    cor2: "#FFFFFF",
    prestigio: 85,
    torcida: 200000000,
    estadio_cap: 64642,
    saldo: 400000000,
    file_key: "benfica",
    estadio_nome: "Estadio da Luz",
    patrocinador: "Fly Emirates",
    escudo_url: getIntlEscudo("benfica"),
    divisao: "primeira_liga",
    regiao: "europa",
    pais: "Portugal"
  },
  {
    nome: "Porto",
    curto: "POR",
    cidade: "Porto",
    estado: "Portugal",
    cor1: "#003DA5",
    cor2: "#FFFFFF",
    prestigio: 84,
    torcida: 180000000,
    estadio_cap: 50033,
    saldo: 380000000,
    file_key: "porto",
    estadio_nome: "Estadio do Dragao",
    patrocinador: "Betano",
    escudo_url: getIntlEscudo("porto"),
    divisao: "primeira_liga",
    regiao: "europa",
    pais: "Portugal"
  },
  {
    nome: "Sporting CP",
    curto: "SCP",
    cidade: "Lisboa",
    estado: "Portugal",
    cor1: "#0F9D58",
    cor2: "#FFFFFF",
    prestigio: 82,
    torcida: 150000000,
    estadio_cap: 50095,
    saldo: 350000000,
    file_key: "sporting",
    estadio_nome: "Estadio Jose Alvalade",
    patrocinador: "Macron",
    escudo_url: getIntlEscudo("sporting"),
    divisao: "primeira_liga",
    regiao: "europa",
    pais: "Portugal"
  },
  {
    nome: "Braga",
    curto: "BRA",
    cidade: "Braga",
    estado: "Portugal",
    cor1: "#E30613",
    cor2: "#FFFFFF",
    prestigio: 75,
    torcida: 60000000,
    estadio_cap: 30286,
    saldo: 200000000,
    file_key: "braga",
    estadio_nome: "Estadio Municipal de Braga",
    patrocinador: "Hummel",
    escudo_url: getIntlEscudo("braga"),
    divisao: "primeira_liga",
    regiao: "europa",
    pais: "Portugal"
  },
  {
    nome: "Vitoria Guimaraes",
    curto: "VSC",
    cidade: "Guimaraes",
    estado: "Portugal",
    cor1: "#000000",
    cor2: "#FFFFFF",
    prestigio: 70,
    torcida: 40000000,
    estadio_cap: 30029,
    saldo: 100000000,
    file_key: "vitoria_guimaraes",
    estadio_nome: "Estadio D. Afonso Henriques",
    patrocinador: "Macron",
    escudo_url: getIntlEscudo("vitoria_guimaraes"),
    divisao: "primeira_liga",
    regiao: "europa",
    pais: "Portugal"
  },
  {
    nome: "Santa Clara",
    curto: "STC",
    cidade: "Ponta Delgada",
    estado: "Portugal",
    cor1: "#E30613",
    cor2: "#FFFFFF",
    prestigio: 62,
    torcida: 15000000,
    estadio_cap: 12500,
    saldo: 50000000,
    file_key: "santa_clara",
    estadio_nome: "Estadio de Sao Miguel",
    patrocinador: "Lacatoni",
    escudo_url: getIntlEscudo("santa_clara"),
    divisao: "primeira_liga",
    regiao: "europa",
    pais: "Portugal"
  },
  {
    nome: "Rio Ave",
    curto: "RAF",
    cidade: "Vila do Conde",
    estado: "Portugal",
    cor1: "#0F9D58",
    cor2: "#FFFFFF",
    prestigio: 63,
    torcida: 18000000,
    estadio_cap: 12820,
    saldo: 55000000,
    file_key: "rio_ave",
    estadio_nome: "Estadio dos Arcos",
    patrocinador: "Lusosensi",
    escudo_url: getIntlEscudo("rio_ave"),
    divisao: "primeira_liga",
    regiao: "europa",
    pais: "Portugal"
  },
  {
    nome: "Famalicao",
    curto: "FAM",
    cidade: "Vila Nova de Famalicao",
    estado: "Portugal",
    cor1: "#003DA5",
    cor2: "#FFFFFF",
    prestigio: 65,
    torcida: 20000000,
    estadio_cap: 5307,
    saldo: 60000000,
    file_key: "famalicao",
    estadio_nome: "Estadio Municipal de Famalicao",
    patrocinador: "Macron",
    escudo_url: getIntlEscudo("famalicao"),
    divisao: "primeira_liga",
    regiao: "europa",
    pais: "Portugal"
  },
  {
    nome: "Estoril Praia",
    curto: "EST",
    cidade: "Estoril",
    estado: "Portugal",
    cor1: "#FFCC00",
    cor2: "#003DA5",
    prestigio: 60,
    torcida: 12000000,
    estadio_cap: 8015,
    saldo: 40000000,
    file_key: "estoril",
    estadio_nome: "Estadio Antonio Coimbra da Mota",
    patrocinador: "Joma",
    escudo_url: getIntlEscudo("estoril"),
    divisao: "primeira_liga",
    regiao: "europa",
    pais: "Portugal"
  },
  {
    nome: "Casa Pia",
    curto: "CPT",
    cidade: "Lisboa",
    estado: "Portugal",
    cor1: "#0F9D58",
    cor2: "#FFFFFF",
    prestigio: 58,
    torcida: 10000000,
    estadio_cap: 9288,
    saldo: 35000000,
    file_key: "casa_pia",
    estadio_nome: "Estadio Pina Manique",
    patrocinador: "Hummel",
    escudo_url: getIntlEscudo("casa_pia"),
    divisao: "primeira_liga",
    regiao: "europa",
    pais: "Portugal"
  }
]

// =============================================
// EXPORTACAO DE TODOS OS TIMES INTERNACIONAIS
// =============================================
export const allInternationalTeams = [
  ...premierLeagueTeams,
  ...laLigaTeams,
  ...serieAItaTeams,
  ...bundesligaTeams,
  ...ligue1Teams,
  ...saudiProTeams,
  ...mlsTeams,
  ...ligaMXTeams,
  ...primeiraLigaTeams,
]

// Funcao para obter times por liga
export function getTeamsByLeague(league: Divisao): Team[] {
  switch (league) {
    case "premier_league":
      return premierLeagueTeams
    case "la_liga":
      return laLigaTeams
    case "serie_a_ita":
      return serieAItaTeams
    case "bundesliga":
      return bundesligaTeams
    case "ligue_1":
      return ligue1Teams
    case "saudi_pro":
      return saudiProTeams
    case "mls":
      return mlsTeams
    case "liga_mx":
      return ligaMXTeams
    case "primeira_liga":
      return primeiraLigaTeams
    default:
      return []
  }
}

// Informacoes das ligas
export const leagueInfo: Record<string, { name: string; country: string; region: string; logo?: string }> = {
  premier_league: { name: "Premier League", country: "Inglaterra", region: "europa" },
  la_liga: { name: "La Liga", country: "Espanha", region: "europa" },
  serie_a_ita: { name: "Serie A", country: "Italia", region: "europa" },
  bundesliga: { name: "Bundesliga", country: "Alemanha", region: "europa" },
  ligue_1: { name: "Ligue 1", country: "Franca", region: "europa" },
  saudi_pro: { name: "Saudi Pro League", country: "Arabia Saudita", region: "asia" },
  mls: { name: "MLS", country: "Estados Unidos", region: "americas" },
  liga_mx: { name: "Liga MX", country: "Mexico", region: "americas" },
  primeira_liga: { name: "Primeira Liga", country: "Portugal", region: "europa" },
}
